# Generated by Django 3.2.5 on 2021-08-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('cleared', 'CLEARED')], default='pending', max_length=200),
        ),
    ]
