# Generated by Django 3.2.5 on 2021-08-11 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210803_1131'),
        ('payments', '0002_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
