# Generated by Django 3.2.5 on 2021-08-17 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_programme_image'),
        ('payments', '0004_studentbalance_studentdeposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('programme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schools.programme')),
            ],
        ),
    ]
