# Generated by Django 3.2.5 on 2021-08-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='contact_number_1',
            field=models.CharField(default='+260', max_length=20),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='contact_number_2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
