# Generated by Django 3.2.5 on 2021-08-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210818_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
