# Generated by Django 3.2.5 on 2021-08-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_websitesetting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='background_image',
            field=models.ImageField(default='defaults/nurses.jpg', upload_to='website/background'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='first_slide_image',
            field=models.ImageField(default='defaults/slide1.jpg', upload_to='website/slide'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='library_image',
            field=models.ImageField(default='defaults/books.png', upload_to='library'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='logo',
            field=models.ImageField(default='defaults/logo.png', upload_to='website'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='prgrammes_image',
            field=models.ImageField(default='defaults/programmes.png', upload_to='programmes'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='second_slide_image',
            field=models.ImageField(default='defaults/slide2.jpg', upload_to='website/slide'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='short_courses_image',
            field=models.ImageField(default='defaults/short-courses.png', upload_to='short_courses'),
        ),
    ]
