# Generated by Django 3.2.5 on 2021-07-23 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0004_delete_student'),
        ('schools', '0003_auto_20210723_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_type', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('masters', 'Masters'), ('phd', 'Phd')], max_length=200)),
                ('highest_qualification', models.CharField(choices=[('high_school', 'Grade 12'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('masters', 'Masters'), ('phd', 'Phd')], max_length=200)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admissions.profile')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.programme')),
            ],
        ),
    ]
