# Generated by Django 3.2.5 on 2021-07-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_type',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('masters', 'Masters'), ('phd', 'Phd')], default='undergraduate', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='highest_qualification',
            field=models.CharField(choices=[('high_school', 'Grade 12'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('masters', 'Masters'), ('phd', 'Phd')], default='high_school', max_length=200),
        ),
    ]
