# Generated by Django 3.2.5 on 2021-07-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_school_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='agricultural_science',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='art',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='biology',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='chemistry',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='civic_education',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='commerce',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='english_language',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='english_literature',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='food_nutrition_and_home_management',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='geography',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='geometric_and_mechanical_drawing',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='history',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='human_and_social_biology',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='information_technology',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='local_language',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='mathematics',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='metal_work',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='nrc',
            field=models.FileField(null=True, upload_to='student_uploads'),
        ),
        migrations.AddField(
            model_name='student',
            name='nutrition',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_photo',
            field=models.FileField(null=True, upload_to='student_uploads'),
        ),
        migrations.AddField(
            model_name='student',
            name='physics',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='principles_of_accounts',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='religious_education',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='results_transcript',
            field=models.FileField(null=True, upload_to='student_uploads'),
        ),
        migrations.AddField(
            model_name='student',
            name='science',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='second_choice',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='secondary_school_attended',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='third_choice',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='wood_work',
            field=models.CharField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, max_length=200),
        ),
    ]
