# Generated by Django 3.2.5 on 2021-08-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210730_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='agricultural_science',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='art',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='biology',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='chemistry',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='civic_education',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='commerce',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='english_language',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='english_literature',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='food_nutrition_and_home_management',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='geography',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='geometric_and_mechanical_drawing',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='history',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='human_and_social_biology',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='information_technology',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='local_language',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='mathematics',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='metal_work',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='nutrition',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='physics',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='principles_of_accounts',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='religious_education',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='science',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='wood_work',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0),
        ),
    ]
