# Generated by Django 3.2.5 on 2021-07-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='code',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programme',
            name='field_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programme',
            name='practicals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='type',
            field=models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('masters', 'Masters'), ('phd', 'Phd')], default='diploma', max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(default='', max_length=200),
        ),
    ]
