# Generated by Django 3.2.5 on 2021-08-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20210723_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='image',
            field=models.ImageField(default='website/assets/images/logo.png', upload_to='programme_uploads'),
        ),
    ]
