# Generated by Django 3.2.5 on 2021-07-23 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_names', models.CharField(max_length=200)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=200)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(default='zambia', max_length=200)),
                ('national_id', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=200)),
                ('physical_address', models.CharField(max_length=200)),
                ('postal_address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('next_of_kin_full_name', models.CharField(max_length=200)),
                ('next_of_kin_email', models.EmailField(max_length=200)),
                ('next_of_kin_phone', models.CharField(max_length=200)),
                ('next_of_kin_province', models.CharField(max_length=200)),
                ('next_of_kin_town', models.CharField(max_length=200)),
                ('next_of_kin_physical_address', models.CharField(max_length=200)),
                ('next_of_kin_postal_address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
