# Generated by Django 3.2.5 on 2021-07-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_auto_20210723_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
